- name: Hello
  hosts: all
  sources:
    - ansible.eda.range:
        limit: 100
      filters:
        - benthomasson.eda.poster:
            webhook_url:  https://localhost:8000/payloads
  rules:
  - name: hi
    condition: event.i is defined
    action:
      debug:
        msg: "Hi {{event}}"
